#! /usr/bin/env bash
#
# Filename: make-docker
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 February 2025
# Last Modified: Saturday 01 March 2025, 20:13
# $Id:$
# Edit Time: 0:49:18
# Description:
#
# Copyright: (C) 2025 Olivier Sirol <czo@free.fr>

IMG=czo-rescue-debian

# Determine the path to the git repository
curdir="$(dirname $(realpath $0))"
repodir="$(realpath ${curdir}/..)"
echo "=> curdir=${curdir}"
echo "=> repodir=${repodir}"

docker build -t $IMG ${repodir}/docker

# Run the build process in the container
docker run --rm --pids-limit=4096 --user 0:0 --privileged --workdir /workspace --volume=${repodir}:/workspace -h $IMG -it $IMG \
    /bin/bash /workspace/make-czo-rescue-debian-iso "$@"
    # /bin/bash

