#! /usr/bin/env bash
#
# Filename: make-docker
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# File Created: 03 February 2025
# Last Modified: Sunday 02 March 2025, 11:38
# $Id: make-docker,v 1.42 2025/03/02 11:38:37 czo Git $
# Edit Time: 0:59:50
# Description:
#
#    docker build and run for czo-rescue-debian
#    debug arg is for debug!
#
# Copyright: (C) 2025 Olivier Sirol <czo@free.fr>

IMG=czo-rescue-debian

# Determine the path to the git repository
curdir="$(dirname $(realpath $0))"
repodir="$(realpath ${curdir}/..)"
echo "=> curdir=${curdir}"
echo "=> repodir=${repodir}"

docker build -t $IMG ${repodir}/docker

if [ "X$1" = "Xdebug" ]; then
    docker run --rm --pids-limit=4096 --user 0:0 --privileged --workdir /workspace --volume=${repodir}:/workspace -h $IMG -it $IMG /bin/bash
    exit 1
fi

docker run --rm --pids-limit=4096 --user 0:0 --privileged --workdir /workspace --volume=${repodir}:/workspace -h $IMG -it $IMG /bin/bash /workspace/make-czo-rescue-debian-iso "$@"
